 select distinct --* 
	 TABLE_CATALOG + '.' + TABLE_SCHEMA	[SCHEMA]
	,TABLE_NAME
	,COLUMN_NAME
	,ORDINAL_POSITION [POS]
	,DATA_TYPE
	,CHARACTER_MAXIMUM_LENGTH [CHAR_MAX_LEN]
	,IS_NULLABLE	
	,NUMERIC_PRECISION
	,CHARACTER_OCTET_LENGTH [CHAR_OCTET+LEN]
	,NUMERIC_PRECISION_RADIX [NUM_PREC_RADIX]
	,COLUMN_DEFAULT
	,NUMERIC_SCALE
	,DATETIME_PRECISION
	,CHARACTER_SET_CATALOG
	,CHARACTER_SET_SCHEMA
	,CHARACTER_SET_NAME
	,COLLATION_CATALOG
	,COLLATION_SCHEMA
	,COLLATION_NAME
	,DOMAIN_CATALOG
	,DOMAIN_SCHEMA
	,DOMAIN_NAME


from INFORMATION_SCHEMA.columns
where TABLE_SCHEMA = 'dbo' and TABLE_NAME like 'v_bts%'
order by ORDINAL_POSITION


